{{- if .Values.configMaps.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.configMaps.blue.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.globalLabels | nindent 4 }}
    app.kubernetes.io/component: blue-config
data:
{{ toYaml .Values.configMaps.blue.data | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.configMaps.green.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.globalLabels | nindent 4 }}
    app.kubernetes.io/component: green-config
data:
{{ toYaml .Values.configMaps.green.data | indent 2 }}
{{- end }}
